#!/bin/bash

get_apn() {
	case $1 in
	"Verizon" | "VZW") echo "vzwinternet" ;;
	esac
}
connect() {
	m=$1
	# Power on the radio
	echo "Checking state on $m..."
	if [ "disabled" == "$(mmcli -m $m | grep state | grep -v power | awk '{print $3}')" ]; then
		mmcli -m $m -e
		echo "$m enabled"
	fi
	# Get Modem Info
	c=$(mmcli -m $m | grep ports | awk -F"(qmi)" '{print $1}' | awk '{print $(NF-1)}')
	i=$(mmcli -m $m | grep ports | awk -F"(net)" '{print $1}' | awk '{print $(NF-1)}')
	o=$(mmcli -m $m | grep 'operator name' | awk '{$1=""; $2=""; $3=""; print $0}' | tr -d \'\" | xargs)
	# Determine connection
	if [ -z "$(nmcli c | grep $c)" ]; then
		nmcli c add save yes type gsm ifname $c con-name $i autoconnect yes apn $(get_apn $o)
	else
		if [ "$(get_apn $o)" != "$(nmcli c show $i | grep gsm.apn | awk '{print $2}')" ]; then
			nmcli c del $i
			connect $m
		fi
	fi
}

if [ -z "$1" ]; then
	modems=($(mmcli -L | grep -v Found | awk '{print $1}'))
	for m in "${modems[@]}"
	do
		connect $m
	done
else 
	modems=($(mmcli -L | grep -v Found | awk '{print $1}'))
	for m in "${modems[@]}"
	do
		if [ "$1" == "$m" ] || [ "$1" == "$(echo $m | awk -F/ '{print $NF}')" ] || [ "$1" == "$(mmcli -m 0 | grep ports | awk -F"(net)" '{print $1}' | awk '{print $(NF-1)}')" ]; then
			connect $m
		fi
	done
fi
